version: "4.22.1"

services:
  mysql:
    image: mysql:latest
    command: [ "mysqld", "--mysql-native-password=ON" ]

    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - pmfr-network
    volumes:
      - ${CAMINHO_PASTA_MYSQL}:/var/lib/mysql/
    env_file:
      - ./config/db.env

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    networks:
      - pmfr-network
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql:
  persistent:


networks:
  pmfr-network:
    external: true
