version: "4.22.1"

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - thiago_network
    volumes:
      - mysql:/var/lib/mysql/
    env_file:
       - ./config/db.env
volumes:
  mysql:
  persistent:


networks:
  thiago_network:
    external: true
  